ansible/app/views/groups.py
# -*- coding: utf8 -*-

from flask import Blueprint, g, render_template, redirect, url_for
from app.forms.groups import AddGroupForm, EditGroupForm
from collections import defaultdict

from app import permision

blueprint = Blueprint('groups', __name__)


@blueprint.route('/')
@permision
def index():
    groups = g.mysql_db.query("select group_name,group_id,description,group_concat(alias) \
            as members from (select host_id,id as group_id,alias,name as \
            group_name,description from groups left join (select host_id,group_id, alias \
            from host_group inner join hosts on host_group.host_id=hosts.id) A \
            on groups.id=A.group_id) aa group by group_id")
    return render_template('groups.html', groups=groups)


@blueprint.route('/add', methods=['GET', 'POST'])
@permision
def add():
    form = AddGroupForm()
    if form.validate_on_submit():
        name = form.name.data
        description = form.description.data
        if description:
            g.mysql_db.execute("INSERT INTO groups(name, description) \
                    VALUES(%s, %s)", name, description)
        else:
            g.mysql_db.execute("INSERT INTO groups(name) \
                    VALUES(%s)", name)

        return redirect(url_for('.index'))
    return render_template('add_group.html', form=form)


def get_all_alias():
    hosts = g.mysql_db.query('select id,alias, count(distinct alias) from \
            hosts group by alias')
    results = []
    for host in hosts:
        results.append((unicode(host.get('id')),host.get('alias')))
    return results


def get_members_by_group(group):
    members_d = g.mysql_db.get("select group_name,group_id, \
            group_concat(alias) as members,group_concat(host_id) \
            as members_id from (select host_id,id \
            as group_id,alias,name as group_name from groups \
            left join (select host_id,group_id, alias from \
            host_group inner join hosts on host_group.host_id=hosts.id) A \
            on groups.id=A.group_id) aa where group_name=%s", group)
    if members_d.get('members'):
        return (members_d.get('group_id'),
                members_d.get('members').split(','),
                members_d.get('members_id').split(','))
    else:
        return (members_d.get('group_id'), [],[])


@blueprint.route('/<group>/edit', methods=['GET', 'POST'])
@permision
def edit(group):
    form = EditGroupForm()
    form.selected_members.choices = get_all_alias()
    group_id, cur_members, cur_members_id = get_members_by_group(group)
    gp = g.mysql_db.get("select * from groups where name=%s", group)
    if form.validate_on_submit():
        new_members_id = form.selected_members.data
        description = form.description.data
        if description:
            g.mysql_db.execute("update groups set description=%s where name=%s",
                    description, group)

        del_members_id = list(set(cur_members_id) - set(new_members_id))
        ins_members_id = list(set(new_members_id) - set(cur_members_id))
        if del_members_id:
            g.mysql_db.executemany("delete from host_group where group_id=%s \
                    and host_id=%s", [(group_id, i) for i in del_members_id])
        if ins_members_id:
            g.mysql_db.executemany("insert into host_group(group_id,host_id) \
                    value(%s, %s)", [(group_id, i) for i in ins_members_id])
        return redirect(url_for('.index'))
    return render_template('edit_group.html', group=group, cur_members=cur_members,
            form=form, gp=gp)

ansible/app/views/hosts.py
# -*- coding: utf8 -*-

import pickle
import ast
import time
from flask import Blueprint, g, render_template, request, redirect, url_for
from ansible.runner import Runner

from app import app
from app import utils as autils
from app import permision
from app.forms.hosts import AddHostForm, EditHostForm
from app.forms.hosts import AddSSHKeyForm


blueprint = Blueprint("hosts", __name__)


@blueprint.route('/')
@permision
def index():
    hosts = g.mysql_db.query("SELECT * from hosts")
    return render_template('hosts.html', hosts=hosts)


def get_alias_info(pattern,remote_user):
    runner = Runner(
            module_name='setup',
            module_args='',
            pattern=pattern,
            inventory=autils.get_inventory(g.mysql_db),
            remote_user=remote_user)
    info = runner.run()

    results = {}

    if info['contacted']:
        if not info['contacted'][pattern].has_key('failed'):
            facts = info['contacted'][pattern]['ansible_facts']
            # Server info
            results['system_vendor'] = facts['ansible_system_vendor']
            results['product_name'] = facts['ansible_product_name']
            results['product_serial'] = facts['ansible_product_serial']
            # System info
            results['distribution'] = facts['ansible_distribution']
            results['distribution_version'] = facts['ansible_distribution_version']
            results['architecture'] = facts['ansible_architecture']
            results['kernel'] = facts['ansible_kernel']
            # Cpu info 
            results['processor_count'] = facts['ansible_processor_count']
            results['processor_cores'] = facts['ansible_processor_cores']
            results['processor_vcpus'] = facts['ansible_processor_vcpus']
            results['processor_threads_per_core'] = facts['ansible_processor_threads_per_core']
            results['processor'] = set(facts['ansible_processor'])
            # Swap info
            results['swaptotal_mb'] = facts['ansible_swaptotal_mb']
            results['swapfree_mb'] = facts['ansible_swapfree_mb']
            # Mem info
            results['memtotal_mb'] = facts['ansible_memtotal_mb']
            results['memfree_mb'] = facts['ansible_memfree_mb']
            # Disk info
            results['devices'] = facts['ansible_devices']
            # Mount info
            results['mounts'] = facts['ansible_mounts']
            # Ip info
            results['default_ipv4'] = facts['ansible_default_ipv4']
            results['all_ipv4_addresses'] = facts['ansible_all_ipv4_addresses']
            # Software 
            results['selinux'] = facts['ansible_selinux']
            results['python_version'] = facts['ansible_python_version']
        else:
            facts = info['contacted'][pattern]
            results['failed'] = facts['failed']
            results['msg'] = facts['msg']
    elif info['dark']:
        facts = info['dark'][pattern] 
        results['failed'] = facts['failed']
        results['msg'] = facts['msg']
    else:
        results['failed'] = False
        results['msg'] = "host not found"

    return results


@blueprint.route('/host/<alias>/', methods=['GET', 'POST'])
@permision
def show_alias(alias):
    alias_info = g.mysql_db.get("SELECT * FROM hosts LEFT JOIN host_info \
            ON hosts.id=host_info.host_id WHERE alias=%s", alias)
    if request.method == 'POST':
        info = get_alias_info(alias_info.get('alias'), alias_info.get('remote_user'))
        last_update = time.time()
        info['host_id'] = alias_info.get('id')
        info['last_update'] = last_update
        if info.get('failed'):
            g.mysql_db.execute("REPLACE INTO host_info (host_id, last_update, failed, msg) \
                    VALUES (%s, %s, %s, %s)", info['host_id'], info['last_update'], 
                    info['failed'], info['msg'])
        else:
            cloums = ' ,'.join(['"%s"'] * len(info.keys()))
            sql = "REPLACE INTO host_info (%s) VALUES (%s)" % (' ,'.join(info.keys()), cloums)
            g.mysql_db.execute(sql % tuple(info.values()))
        return redirect(url_for('.show_alias', alias=alias))
    return render_template('show_alias.html', alias_info=alias_info)


@blueprint.route('/add', methods=['GET', 'POST'])
@permision
def add():
    form = AddHostForm()
    if form.validate_on_submit():
        alias = form.alias.data
        ip = form.ip.data
        ip2 = form.ip2.data
        port = form.port.data
        remote_user = form.remote_user.data
        if ip2:
            g.mysql_db.execute("INSERT INTO hosts(alias, ip, ip2, port, remote_user) \
                    VALUES(%s,%s,%s,%s,%s)", alias, ip, ip2, port, remote_user)
        else:
            g.mysql_db.execute("INSERT INTO hosts(alias, ip, port, remote_user) \
                    VALUES(%s,%s,%s,%s)", alias, ip, port, remote_user)
        return redirect(url_for('.index'))
    return render_template('add_host.html', form=form)


@blueprint.route('/host/<alias>/edit', methods=['GET', 'POST'])
@permision
def edit_host(alias):
    form = EditHostForm()
    if form.validate_on_submit():
        ip = form.ip.data
        ip2 = form.ip2.data
        port = form.port.data
        remote_user = form.remote_user.data
        if ip2 and ip2 != u'None':
            g.mysql_db.execute("UPDATE hosts SET ip=%s, ip2=%s, port=%s, remote_user=%s \
                    WHERE alias=%s", ip, ip2, port, remote_user, alias)
        else:
            g.mysql_db.execute("UPDATE hosts SET ip=%s, port=%s, remote_user=%s \
                    WHERE alias=%s", ip, port, remote_user, alias)
        return redirect(url_for('.index'))
    host = g.mysql_db.get('SELECT * FROM hosts WHERE alias=%s', alias)
    return render_template('edit_host.html', host=host, form=form)


@blueprint.route('/host/<alias>/add_sshkey', methods=['GET', 'POST'])
@permision
def add_sshkey(alias):
    form = AddSSHKeyForm()
    if form.validate_on_submit():
        remote_user = form.remote_user.data
        remote_pass = form.remote_pass.data

        runner = Runner(
                module_name='authorized_key',
                module_args={'user': remote_user,
                             'key': open(app.config['ANSIBLE_KEY']).read()
                             },
                pattern=alias,
                inventory=autils.get_inventory(g.mysql_db),
                remote_user=remote_user,
                remote_pass=remote_pass)
        info = runner.run()
        return redirect(url_for('.index'))

    host = g.mysql_db.get('SELECT * FROM hosts WHERE alias=%s', alias)
    return render_template('add_sshkey.html', host=host, form=form)

ansible/app/views/jobs.py
# -*- coding: utf8 -*-

import os
import ast
import time
import glob
import codecs
from collections import defaultdict
from passlib.hash import sha512_crypt
import pickle
from amqplib import client_0_8 as amqp
from flask import Blueprint, g, render_template, request, redirect, url_for

from app import app
from app import permision
from app.forms.jobs import AddGeneralJobForm
from app.forms.jobs import JobAddUserForm
from app.forms.jobs import JobDelUserForm
from app.forms.jobs import JobAddUserByPubkeyForm
from app.forms.jobs import ReActionForm
from app.forms.jobs import JobMysqlForm
from app.forms.jobs import JobPhpForm


blueprint = Blueprint('jobs', __name__)


def send2amqp(yml_temp_name, args):
    started = str(int(time.time()))
    g.mysql_db.execute("INSERT INTO jobs(started, template_name, args) \
            VALUES(%s, %s, %s)", started, yml_temp_name, pickle.dumps(args))

    body = (started, yml_temp_name, args)
    msg = amqp.Message(pickle.dumps(body))
    msg.properties['delivery_mode'] = 2    #持久化消息
    g.amqp_chan.basic_publish(msg, exchange="sorting_room", routing_key="json")


def get_alias():
    hosts = g.mysql_db.query('select A.id,alias,ip,port,remote_user, \
            name as group_name from \
            (select hosts.id,alias,ip,port,remote_user,group_id from hosts \
            left join host_group on hosts.id=host_group.host_id) A \
            left join groups on A.group_id=groups.id')
    r = defaultdict(list)
    for host in hosts:
        r[host.get('group_name')].append(host)
    results = []
    for i in r:
        results.append(("{}".format(i),"*{}".format(i)))
        for j in r.get(i):
            results.append((j.get('alias'),j.get('alias')))
    return results


@blueprint.route('/', methods=['GET', 'POST'])
@permision
def index():
    form = ReActionForm()
    if form.validate_on_submit():
        yml_temp_name = form.yml_temp_name.data
        args = ast.literal_eval(form.argss.data)
        send2amqp(yml_temp_name, args)
        return redirect(url_for('jobs.index'))
    jobs = g.mysql_db.query("SELECT * FROM jobs LIMIT 1000")
    return render_template('jobs.html', jobs=jobs, form=form)


@blueprint.route('/add_general', methods=['GET', 'POST'])
@permision
def add_general():
    form = AddGeneralJobForm()
    form.yml_temp_name.choices = [(i, i) for i in os.listdir(app.config['YML_TEMP_PATH']) if i[0] != '_']
    form.selected_alias.choices = get_alias()
    if form.validate_on_submit():
        host = ':'.join(form.selected_alias.data)
        user = form.remote_user.data
        yml_temp_name = form.yml_temp_name.data
        args = {'host': host,
                'user': user}
        send2amqp(yml_temp_name, args)
        return redirect(url_for("jobs.index"))

    return render_template('add_general_job.html', form=form)


@blueprint.route('/add_other', methods=['GET', 'POST'])
@permision
def add_other():
    return render_template('add_other_job.html')


@blueprint.route('/add_user', methods=['GET', 'POST'])
@permision
def add_user():
    form = JobAddUserForm()
    form.selected_alias.choices = get_alias()
    if form.validate_on_submit():
        host = ':'.join(form.selected_alias.data)
        user = form.remote_user.data
        username = form.username.data
        password = form.password.data
        passwd_sha512 = sha512_crypt.encrypt(password)
        yml_temp_name = form.yml_temp_name.data
        args = {'host': host,
                'user': user,
                'username': username,
                'password': passwd_sha512
                }
        send2amqp(yml_temp_name, args)
        return redirect(url_for("jobs.index"))
    
    yml_temp_name = '_add_user'
    return render_template('job_add_user.html',form=form,
            yml_temp_name=yml_temp_name)


@blueprint.route('/del_user', methods=['GET', 'POST'])
@permision
def del_user():
    form = JobDelUserForm()
    form.selected_alias.choices = get_alias()
    if form.validate_on_submit():
        host = ':'.join(form.selected_alias.data)
        user = form.remote_user.data
        username = form.username.data
        if username == u'root':
            username = u'test'
        yml_temp_name = form.yml_temp_name.data
        args = {'host': host,
                'user': user,
                'username': username
                }
        send2amqp(yml_temp_name, args)
        return redirect(url_for("jobs.index"))
    
    yml_temp_name = '_del_user'
    return render_template('job_del_user.html',form=form,
            yml_temp_name=yml_temp_name)


@blueprint.route('/add_user_by_pubkey', methods=['GET', 'POST'])
@permision
def add_user_by_pubkey():
    form = JobAddUserByPubkeyForm()
    form.selected_alias.choices = get_alias()
    form.key.choices = [(os.path.basename(i), os.path.basename(i)) for i in glob.glob(os.path.join(app.config['KEYDIR'], '*.pub'))]
    if form.validate_on_submit():
        host = ':'.join(form.selected_alias.data)
        user = form.remote_user.data
        username = form.username.data
        key = form.key.data
        key = codecs.open(os.path.join(app.config['KEYDIR'], key), 'r').read()
        yml_temp_name = form.yml_temp_name.data
        args = {'host': host,
                'user': user,
                'username': username,
                'key': key
                }
        send2amqp(yml_temp_name, args)
        return redirect(url_for("jobs.index"))
    
    yml_temp_name = '_add_user_by_pubkey'
    return render_template('job_add_user_by_pubkey.html',form=form,
            yml_temp_name=yml_temp_name)


@blueprint.route('/mysql', methods=['GET', 'POST'])
@permision
def mysql():
    form = JobMysqlForm()
    form.selected_alias.choices = get_alias()
    if form.validate_on_submit():
        host = ':'.join(form.selected_alias.data)
        user = form.remote_user.data
        mysql_data_dir = form.mysql_data_dir.data
        yml_temp_name = form.yml_temp_name.data
        args = {'host': host,
                'user': user,
                'mysql_data_dir': mysql_data_dir
                }
        send2amqp(yml_temp_name, args)
        return redirect(url_for("jobs.index"))
    
    yml_temp_name = '_mysql5.5'
    return render_template('job_mysql5.5.html',form=form,
            yml_temp_name=yml_temp_name)


@blueprint.route('/php', methods=['GET', 'POST'])
@permision
def php():
    form = JobPhpForm()
    form.selected_alias.choices = get_alias()
    if form.validate_on_submit():
        host = ':'.join(form.selected_alias.data)
        user = form.remote_user.data
        mysql_data_dir = form.mysql_data_dir.data
        yml_temp_name = form.yml_temp_name.data
        args = {'host': host,
                'user': user,
                'mysql_data_dir': mysql_data_dir
                }
        send2amqp(yml_temp_name, args)
        return redirect(url_for("jobs.index"))
    
    yml_temp_name = '_php5.3'
    return render_template('job_php5.3.html',form=form,
            yml_temp_name=yml_temp_name)


@blueprint.route('/jobs_log', methods=['GET', 'POST'])
@permision
def log():
    log = codecs.open(app.config['ANSIBLE_LOG'], encoding='utf-8')
    return render_template('jobs_log.html', logs=log.readlines())


@blueprint.route('/amqp_log', methods=['GET', 'POST'])
@permision
def amqp_log():
    log = codecs.open(app.config['AMQP_LOG'], encoding='utf-8')
    return render_template('amqp_log.html', logs=log.readlines())

ansible/app/templates/add_group.html
{% extends "base.html" %}

{% block content %}
<div>
    <ul class="breadcrumb">
        <li>
            <a href="#">Home</a>
        </li>
        <li>
            <a href="#">Forms</a>
        </li>
    </ul>
</div>
<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-edit"></i> Form Elements</h2>

                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default"><i
                            class="glyphicon glyphicon-cog"></i></a>
                    <a href="#" class="btn btn-minimize btn-round btn-default"><i
                            class="glyphicon glyphicon-chevron-up"></i></a>
                    <a href="#" class="btn btn-close btn-round btn-default"><i
                            class="glyphicon glyphicon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">
				<form role="form" method="post" action={{ url_for('groups.add') }}>
					{{ form.hidden_tag() if form.hidden_tag }}
					{% for f in form if f.type != 'CSRFTokenField' %}
						{% if f.errors %}
						<div class="input-group has-error col-md-4">
							{{ f.label(class_="control-label", for="inputError1") }}
							{{ f(class_="form-control", id="inputError1", placeholder="Enter " + f.label.text) }}
							{% if f.errors %}
								{% for e in f.errors %}
									<div class="alert alert-danger">
										<button type="button" class="close" data-dismiss="alert">&times;</button>
										<strong>Oh snap!</strong> {{ e }}
									</div>
								{% endfor %}
							{% endif %}
						</div>
						{% else %}
						<div class="input-group col-md-4">
							{{ f.label(class_="control-label") }}
							{{ f(class_="form-control", placeholder="Enter " + f.label.text) }}
						</div>
						{% endif %}
					{% endfor %}
					</br>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>

            </div>
        </div>
    </div>
    <!--/span-->

</div><!--/row-->

{% endblock %}

ansible/app/templates/add_host.html
{% extends "base.html" %}

{% block content %}
<div>
    <ul class="breadcrumb">
        <li>
            <a href="#">Home</a>
        </li>
        <li>
            <a href="#">Forms</a>
        </li>
    </ul>
</div>
<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-edit"></i> Form Elements</h2>

                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default"><i
                            class="glyphicon glyphicon-cog"></i></a>
                    <a href="#" class="btn btn-minimize btn-round btn-default"><i
                            class="glyphicon glyphicon-chevron-up"></i></a>
                    <a href="#" class="btn btn-close btn-round btn-default"><i
                            class="glyphicon glyphicon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">
				<form role="form" method="post" action={{ url_for('hosts.add') }}>
					{{ form.hidden_tag() if form.hidden_tag }}
					{% for f in form if f.type != 'CSRFTokenField' %}
						{% if f.errors %}
						<div class="input-group has-error col-md-4">
							{{ f.label(class_="control-label", for="inputError1") }}
							{{ f(class_="form-control", id="inputError1", placeholder="Enter " + f.label.text) }}
							{% if f.errors %}
								{% for e in f.errors %}
									<div class="alert alert-danger">
										<button type="button" class="close" data-dismiss="alert">&times;</button>
										<strong>Oh snap!</strong> {{ e }}
									</div>
								{% endfor %}
							{% endif %}
						</div>
						{% else %}
						<div class="input-group col-md-4">
							{{ f.label(class_="control-label") }}
							{{ f(class_="form-control", placeholder="Enter " + f.label.text) }}
						</div>
						{% endif %}
					{% endfor %}
					</br>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>

            </div>
        </div>
    </div>
    <!--/span-->

</div><!--/row-->

{% endblock %}

ansible/app/templates/admin.html
{% extends "base.html" %}


{% block content %}
{% endblock %}

ansible/app/templates/edit_group.html
{% extends "base.html" %}


{% block content %}
<div>
    <ul class="breadcrumb">
        <li>
            <a href="#">Home</a>
        </li>
        <li>
            <a href="#">Forms</a>
        </li>
    </ul>
</div>
<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-edit"></i> Form Elements</h2>

                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default"><i
                            class="glyphicon glyphicon-cog"></i></a>
                    <a href="#" class="btn btn-minimize btn-round btn-default"><i
                            class="glyphicon glyphicon-chevron-up"></i></a>
                    <a href="#" class="btn btn-close btn-round btn-default"><i
                            class="glyphicon glyphicon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">
				<form role="form" method="post" action={{ url_for('groups.edit', group=group) }}>
					{{ form.hidden_tag() if form.hidden_tag }}
                    <div class="form-group">
                        <label for="exampleInputEmail1">Group Name</label>
						<input type="text" class="form-control" id="exampleInputEmail1" readonly="true" name="name" value="{{ group }}">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Group Description</label>
						<input type="text" class="form-control" id="exampleInputEmail1" name="description" value="{{ gp.description }}">
                    </div>
					<div class="control-group">
						{{ form.selected_members.label(class_="control-label", for="selectError1") }}

						<div class="controls">
							<select id="selectError1" multiple class="form-control" name="selected_members" data-rel="chosen">
								{% for i in form.selected_members.choices %}
									{% if cur_members %}
										{% if i[1] in cur_members %}
										<option value={{ i[0] }} selected>{{ i[1] }}</option>
										{% else %}
										<option value={{ i[0] }}>{{ i[1] }}</option>
										{% endif %}
									{% else %}
									<option value={{ i[0] }}>{{ i[1] }}</option>
									{% endif %}
								{% endfor %}
							</select>
						</div>
						{% if form.selected_members.errors %}
						{% for e in form.selected_members.errors %}
						<div class="alert alert-danger">
							<button type="button" class="close" data-dismiss="alert">&times;</button>
							<strong>Oh snap!</strong> {{ e }}
						</div>
						{% endfor %}
						{% endif %}
					</div>
				<br>
				<button type="submit" class="btn btn-default">Submit</button>
				</form>
            </div>
        </div>
    </div>
    <!--/span-->

</div><!--/row-->
{% endblock %}

ansible/app/templates/groups.html
{% extends "base.html" %}

{% block content %}
                <div>
        <ul class="breadcrumb">
            <li>
                <a href="#">Home</a>
            </li>
            <li>
                <a href="#">Tables</a>
            </li>
        </ul>
    </div>

    <div class="row">
    <div class="box col-md-12">
    <div class="box-inner">
    <div class="box-header well" data-original-title="">
        <h2><i class="glyphicon glyphicon-user"></i> Datatable + Responsive</h2>

        <div class="box-icon">
			<a href={{ url_for('groups.add') }} class="btn btn-round btn-default"><i class="glyphicon glyphicon-cog"></i></a>
            <a href="#" class="btn btn-minimize btn-round btn-default"><i
                    class="glyphicon glyphicon-chevron-up"></i></a>
            <a href="#" class="btn btn-close btn-round btn-default"><i class="glyphicon glyphicon-remove"></i></a>
        </div>
    </div>
    <div class="box-content">
    <table class="table table-striped table-bordered bootstrap-datatable datatable responsive">
    <thead>
    <tr>
        <th>ID</th>
        <th>Group</th>
        <th>Description</th>
        <th>Members</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
	{% for group in groups %}
    <tr>
		<td>{{ group.group_id }}</td>
		<td class="center">{{ group.group_name }}</td>
		<td class="center">{{ group.description }}</td>
		{% if group.members %}
		<td class="center">
			{% for m in group.members|split %}
			<a href="{{ url_for('hosts.show_alias', alias=m) }}">{{ m }}</a>,
			{% endfor %}
		</td>
		{% else %}
		<td class="center">{{ group.members }}</td>
		{% endif %}
        <td class="center">
			<a class="btn btn-success" href={{ url_for('groups.edit', group=group.group_name) }}>
                <i class="glyphicon glyphicon-zoom-in icon-white"></i>
                Edit
            </a>
        </td>
    </tr>
	{% endfor %}
    </tbody>
    </table>
    </div>
    </div>
    </div>
    <!--/span-->

    </div><!--/row-->

{% endblock %}

ansible/app/templates/hosts.html
{% extends "base.html" %}

{% block content %}
                <div>
        <ul class="breadcrumb">
            <li>
                <a href="#">Home</a>
            </li>
            <li>
                <a href="#">Tables</a>
            </li>
        </ul>
    </div>

    <div class="row">
    <div class="box col-md-12">
    <div class="box-inner">
    <div class="box-header well" data-original-title="">
        <h2><i class="glyphicon glyphicon-user"></i> Datatable + Responsive</h2>

        <div class="box-icon">
			<a href={{ url_for('hosts.add') }} class="btn btn-round btn-default"><i class="glyphicon glyphicon-cog"></i></a>
            <a href="#" class="btn btn-minimize btn-round btn-default"><i
                    class="glyphicon glyphicon-chevron-up"></i></a>
            <a href="#" class="btn btn-close btn-round btn-default"><i class="glyphicon glyphicon-remove"></i></a>
        </div>
    </div>
    <div class="box-content">
    <table class="table table-striped table-bordered bootstrap-datatable datatable responsive">
    <thead>
    <tr>
        <th>ID</th>
        <th>Alias</th>
        <th>Ip</th>
        <th>Ip2</th>
        <th>Port</th>
        <th>Remote User</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
	{% for host in hosts %}
    <tr>
		<td>{{ host.id }}</td>
		<td class="center">{{ host.alias }}</td>
		<td class="center">{{ host.ip }}</td>
		<td class="center">{{ host.ip2 }}</td>
		<td class="center">{{ host.port }}</td>
		<td class="center">{{ host.remote_user }}</td>
        <td class="center">
			<a class="btn btn-success" href={{ url_for("hosts.show_alias", alias=host.alias) }}>
                <i class="glyphicon glyphicon-zoom-in icon-white"></i>
                View
            </a>
			<a class="btn btn-info" href={{ url_for("hosts.edit_host", alias=host.alias) }}>
                <i class="glyphicon glyphicon-zoom-in icon-white"></i>
                Edit
            </a>
			<a class="btn btn-info" href={{ url_for("hosts.add_sshkey", alias=host.alias) }}>
                <i class="glyphicon glyphicon-zoom-in icon-white"></i>
                SSHKey
            </a>
        </td>
    </tr>
	{% endfor %}
    </tbody>
    </table>
    </div>
    </div>
    </div>
    <!--/span-->

    </div><!--/row-->

{% endblock %}